### PR TITLE
Apply css style defined by design.

### LINKED ISSUE #550: retry uploads: failed media specs
Tweaks to the style to meet @thianhlu's specs:

Background
-webkit-filter: blur(4px) grayscale(0.3);
Can we try and clip the borders/edges so they are not blurred? We would probably have to put inside a div like (http://stackoverflow.com/questions/12224320/defined-edges-with-css3-filter-blur).

Failed text
text-shadow: 0 1px 2px rgba(0,0,0,.06);
font-size: 20px

Retry Icon
opacity: 0.9;
background: #FFFFFF;
height: 54px
width 54px

Retry Icon circle
opacity: 0.9;
border: 4px solid #FFFFFF;
-webkit-border-radius: 60px
height: 120px
width 120px

cc @SergioEstevao

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fix #550 

cc @bummytime or @aerych can you please review.

### CODE REVIEW

**Comment by bummytime** [comment]
:shipit:

**Comment by thianhlu** [comment]
Can you attach a screengrab?

**Comment by SergioEstevao** [comment]
screen shot 2015-02-09 at 23 08 20

**Comment by thianhlu** [comment]
Looks awesome @SergioEstevao 

Can you add some space between the icon and `Failed` label. You can use the same spacing that @aerych is using on Edit Image

**Comment by SergioEstevao** [comment]
screen shot 2015-02-09 at 23 20 55

**Comment by thianhlu** [comment]
Sorry to nit. Can you move retry icon down 2px within the circle border. 

Also instructions (circle and label) are meant to be centered vertically and horizontally within the image overlay. I believe @aerych has this logic/spacing already implemented, can we leverage his otherwise I can provide exact spacing later today. cc @meremagee

**Comment by thianhlu** [comment]
I meant 1px, updated comment above ^

**Pull request merged**
